### ISSUE TITLE
2 problems

### ISSUE THREAD

**Issue by askfriends** [meteor314/gDrive#2]
First it doesn't preserve folder structure.
Second it doesn't support uploading to team drive, getting following error:
`Error uploading C:\Users\ji\Documents\gDrive\test\9.json: <HttpError 404 when requesting https://www.googleapis.com/upload/drive/v3/files?fields=id&alt=json&uploadType=multipart returned "File not found: 1vI5hf_Jslyxfhfhgfdffsdgf1OJ.". Details: "[{'message': 'File not found: 1hgfgfC_Jslyx1OhggjghjhgjISJ.', 'domain': 'global', 'reason': 'notFound', 'location': 'fileId', 'locationType': 'parameter'}]">`

**Comment by meteor314** [comment]
Hey thank you for your feedback, forgot to add share drive support, please  let me know if it's working fine for you : in gdrive2 branch https://github.com/meteor314/gDrive/tree/gdrive2

**Comment by askfriends** [comment]
> Hey thank you for your feedback, forgot to add share drive support, please let me know if it's working fine for you : in gdrive2 branch https://github.com/meteor314/gDrive/tree/gdrive2

ok i got first error which was about wrong spelling in config.ini, i corrected it then i got this error:
```
Traceback (most recent call last):
  File "c:\Users\j\Documents\gDrive\gDrive-gdrive2\main.py", line 9, in <module>
    isRunning = config['RUN']['IS_RUNNING']
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\configparser.py", line 965, in __getitem__
    raise KeyError(key)
KeyError: 'RUN'
```

**Comment by meteor314** [comment]
can you just try with this `config.ini`, please i think this should work, if yes i will update the documentation. Thanks again.
```sh
[FOLDER]
LOCAL_FOLDER_PATH  = /home/meteor314/Desktop/test
DRIVE_FOLDER_ID =0AL9R7YLLZyi_Uk9XVZ 
IS_SHARE_DRIVE = True
[CONFIG]
DATA_BASE = database.db
[RUN]
IS_RUNNING = 0
[LOG]
LOG_FILE = logs.log
``` 
If it's not working in your side please 
replace in `main.py` 
```py
if __name__ == "__main__":
    # If an error occurs, make sure to set isRunning to 1 in config.ini
    try:
        main()
    except Exception as e:
        print(e)
        config['RUN']['IS_RUNNING'] = '1'
        with open('config.ini', 'w') as configfile:
            config.write(configfile)
    else:
        config['RUN']['IS_RUNNING'] = '0'
        with open('config.ini', 'w') as configfile:
            config.write(configfile)
``` 
by this : 
```py
if __name__ == "__main__":
    # If an error occurs, make sure to set isRunning to 1 in config.ini
    try:
        main()
    except Exception as e:
        print(e)
```

**Comment by askfriends** [comment]
> ```shell
> [FOLDER]
> LOCAL_FOLDER_PATH  = /home/meteor314/Desktop/test
> DRIVE_FOLDER_ID =0AL9R7YLLZyi_Uk9XVZ 
> IS_SHARE_DRIVE = True
> [CONFIG]
> DATA_BASE = database.db
> [RUN]
> IS_RUNNING = 0
> [LOG]
> LOG_FILE = logs.log
> ```

Ok now uploading works but there is still one bug;
It doesnt retain folder structure, it doesnt create folder inside parent folder instead it creates all child folders in the parent folder, i hope u got my point or just create dummy folders and add more sub-folders and try to upload them, u will see all the subfolders are being uploaded in the parent folder. kindly fix it

**Comment by meteor314** [comment]
Okay, just a minor correction. Replace the following line in `folder_structure.py`:

```python
folder_metadata['parents'] = [parent_folder_id]
```
And it should be good. Btw I have updated the code, and everything should work now. Please don't forget to close the issue :), don't forgot to delete `folders.db`  and all subfolders in google drive for testing.

**Comment by askfriends** [comment]
> Okay, just a minor correction. Replace the following line in `folder_structure.py`:
> 
> ```python
> folder_metadata['parents'] = [parent_folder_id]
> ```
> 
> And it should be good. Btw I have updated the code, and everything should work now. Please don't forget to close the issue :), don't forgot to delete `folders.db` and all subfolders in google drive for testing.

yeah i can confirm its working fine now. Thanks a lot.

BTW i want to use this script to upload downloaded files by this tool 
https://github.com/TheKVT/music-dl

basically this tool download tracks from qobuz and other servers and create folders in the parent directory, so i want to use your script to automatically upload all the folders to gdrive.
Will u have a look at the tool i have provided and see if you can add ur script to upload the files, you can run that file in google colab https://colab.research.google.com/
